services:
  postgres:
    image: "postgres:13"
    container_name: imago-core-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
        - ./tmp/postgres:/var/lib/postgresql/data
    env_file:
      - dev.env
    hostname: postgres