server:
  host: "0.0.0.0"
  port: "8080"

firebase:
  credentials: "./configs/admin-key.json"
  projectid: "itss-imago-0000"

database:
  dsn: "postgres://beheo:ANIFHIdndwwid0139@localhost:5432/postgres"